[[querying-istio-metrics-with-prometheus]]
= Querying Istio Metrics With Prometheus

////
Pulled from istio.github.io and converted from Markdown to Asciidoc
////

This process illustrates how to query Istio metrics with Prometheus from the web interface.

The link:/istio-docs/Doc-Installing-ServiceMesh/topics/tutorial-bookinfo.adoc/[Bookinfo] application is used in the examples presented here.

[[before-you-begin]]
== Before You Begin

link:/docs/setup/[Install Istio] in your cluster and deploy an
application.

[[querying-istio-metrics]]
== Querying Istio Metrics

1.  Verify that the `prometheus` service is running in your cluster.
+
In Kubernetes environments, issue the following command:
+
----
kubectl -n istio-system get svc prometheus NAME
CLUSTER-IP EXTERNAL-IP PORT(S) AGE prometheus 10.59.241.54 9090/TCP 2m
----
+
2.  Send traffic to the mesh.
+
For the Bookinfo sample, visit `http://$GATEWAY_URL/productpage` in your
web browser or issue the following command:
+
----
curl http://$GATEWAY_URL/productpage
----
+
[NOTE]
====
`$GATEWAY_URL` is the value set in the
link:/istio-docs/Doc-Installing-ServiceMesh/topics/tutorial-bookinfo.adoc/[Bookinfo] example.
====

3.  Start the Prometheus web interface.
+
In Kubernetes environments, issue this command:
+
----
kubectl -n istio-system port-forward $(kubectl -n
istio-system get pod -l app=prometheus -o
jsonpath=`\{.items[0].metadata.name}') 9090:9090 &
----
+
4. Visit http://localhost:9090/graph in your web browser.

5.  Run a Prometheus query.
+
In the `Expression` input box at the top of the web page, enter the
text: `istio_requests_total` and click *Execute*.
+
The result will resemble this:
+
----
< image width=``100%'' ratio=``42.63%''
link=``./prometheus_query_result.png'' caption=``Prometheus Query
Result'' >
----

[[additional-queries]]
=== Additional Queries

* Total count of all requests to the `productpage` service:
+
----
istio_requests_total\{destination_service=``productpage.default.svc.cluster.local''}
----

* Total count of all requests to `v3` of the `reviews` service:
+
----
istio_requests_total\{destination_service=``reviews.default.svc.cluster.local'',
destination_version=``v3''}
----

* Rate of requests over the past 5 minutes to all instances of the
`productpage` service:
+
----
rate(istio_requests_total\{destination_service=~“productpage.*``,
response_code=''200“}[5m])
----

[[about-the-prometheus-add-on]]
== About the Prometheus Add-On

Mixer includes a built-in https://prometheus.io[Prometheus] adapter
that exposes an endpoint serving generated metric values. The Prometheus
add-on is a Prometheus server preconfigured to scrape Mixer
endpoints to collect the exposed metrics. It provides a mechanism for
persistent storage and querying of Istio metrics.

The configured Prometheus add-on scrapes three endpoints:

1.  *istio-mesh* (`istio-mixer.istio-system:42422`): all Mixer-generated
mesh metrics.
2.  *mixer* (`istio-mixer.istio-system:9093`): all Mixer-specific
metrics for monitoring the Mixer.
3.  *envoy* (`istio-mixer.istio-system:9102`): raw stats generated by
Envoy translated from Statsd to Prometheus.

For more on querying Prometheus, see
https://prometheus.io/docs/querying/basics/[the Prometheus query documentation].

[[cleanup]]
== Cleanup

1. Remove any `kubectl port-forward` processes that are still running:
+
----
killall kubectl
----

2. When you are finished, see the
link:/istio-docs/Doc-Installing-ServiceMesh/topics/tutorial-bookinfo.adoc/[Removing the Bookinfo Application] instructions to
remove the application.
